### ISSUE TITLE
Development progress

### ISSUE THREAD

**Issue by kbumsik** [kbumsik/emJSON#4]
🚧 In progress.
### Adding object type.
- [x] adding it in `json.h` : Done in PR #3 
- [ ] adding it in `emJSON.h`
- [x] adding parser for object type : Done in PR #5 
- [ ] handling buffer inside/outside of parent buffer
### Adding null type (needed for adding object type)
- [x] adding it in `json.h` : Done in PR #3, #5 
- [x] Serialize  : Done in PR #5 
- [ ] adding it in `emJSON.h` 
- [ ] adding parser for null type
- [ ] Proper handling
### Others
- [ ] Delete content size
- [ ] Optimize
- [ ] Automatic adjusting size
- [ ] Compile option for architecture not supporting unaligned access (such as ARM by default)

**Comment by kbumsik** [comment]
~~I will pause developing for a month for other project.~~

**Comment by kbumsik** [comment]
Development resumed.
